### ISSUE TITLE
regarding dependencies

### ISSUE THREAD

**Issue by rictionlessdevelopme** [ballantyne/livecoin#1]
Hey, nice work. I have been fiddling with livecoins API for a few months myself, switch between python and php builds mostly depending on whichever project im working on. 

Have you tried building this in a more slimmed down version? For systems with less get-up? If not thats fine, either way would love to chat sometime, never spoken to anyone who  has worked with livecoin api things before other than myself. You have discord?

**Comment by ballantyne** [comment]
I'm not sure what you are talking about.  I don't think that this module would need a very powerful computer to work well.  Also the other module called livecoin-tcp would allow you to have a proxy that runs on a different machine that would let you send requests from another machine.  

As it is, there aren't that many dependencies.
https://github.com/ballantyne/livecoin/blob/master/package.json

I guess I could just use the standard lib for the http requests and leave out the validation library which isn't really being used yet.  I built the module the way that I did so that it would work well with a proxy because of the rate limiting.  I wanted to be able to have several different bots running at once and still not have problems with the rate limit.  Does that answer your question?

**Comment by rictionlessdevelopme** [comment]
For sure, wasn't even saying anything was wrong with it. I'm just not a node expert, like I said I mainly dev with php and py. Only reason was asking was cause you seem like you know way more node stuff than myself. Sorry about that
